namespace OzzieAI.Agentica
{
    using OzzieAI.Agentica.Providers;
    using OzzieAI.Agentica.Tools;
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Represents a high-autonomy execution entity designed for technical implementation.
    /// The WorkerAgent is optimized for 'Action-Oriented' tasks, utilizing a suite of 
    /// physical tools (File IO, Terminal, Search) to achieve concrete project milestones.
    /// </summary>
    public class WorkerAgent : BaseAgent
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerAgent"/>.
        /// </summary>
        public WorkerAgent(AgentConfig config, IAgentBus bus, DragonMemory memory)
            : base(config, bus, memory) { }

        /// <summary>
        /// Handles operational assignments from the AgentBus.
        /// When a <see cref="MessageType.TaskAssignment"/> is received, the Worker triggers 
        /// its internal ReAct (Reason + Act) loop to fulfill the request.
        /// </summary>
        /// <param name="message">The task metadata and content sent by a Manager or Boss.</param>
        protected override async Task ProcessIncomingMessageAsync(AgentMessage message)
        {
            if (message.Type == MessageType.TaskAssignment)
            {
                // Visual signaling that the 'Hands' of the organization are moving
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine($"\n[Worker {Config.Name}] Task Received: {message.Content}");
                Console.ResetColor();

                // 1. Memory Initialization & Ingestion
                // Ensure the History collection is initialized to prevent null reference exceptions.
                // Memory.History ??= new List<IChatMessage>();

                // Explicitly add the incoming task to the agent's memory as a user prompt.
                // This ensures the agent (and the extraction logic later) has a definitive record 
                // of what triggered this execution cycle.
                Memory.History.Add(new ChatMessage
                {
                    Role = "user",
                    Content = message.Content
                });

                // 2. Ignition: Enter the recursive Thinking Loop inherited from BaseAgent.
                // This kicks off the loop where the LLM autonomously decides to call tools 
                // (e.g., 'file_manager' to read/write, 'terminal_executor' to build).
                await StartTaskAsync(message.Content);

                // 3. Extraction: Identify the final conclusion from the cognitive history.
                // We use null-conditional operators (?.) to safely evaluate the Role, preventing crashes 
                // if a malformed message was injected into the history during the execution loop.
                var lastAssistantMessage = Memory.History
                    .LastOrDefault(m => m.Role?.Equals("assistant", StringComparison.OrdinalIgnoreCase) == true);

                // Safely extract the content, providing a fallback if the LLM failed to generate a final summary.
                string finalReport = lastAssistantMessage?.Content?.ToString()
                    ?? "Task processed, but no descriptive report was generated by the LLM.";

                // 4. Reporting: Close the loop by sending the result back to the Requester.
                // This informs the Manager/Boss that the task is complete and provides the technical evidence.
                await Bus.SendAsync(new AgentMessage(
                    SenderId: Config.Id,
                    ReceiverId: message.SenderId,
                    Type: MessageType.TaskResult,
                    Content: finalReport,
                    Timestamp: DateTime.UtcNow));

                // Visual confirmation that the communication loop has been closed
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                Console.WriteLine($"[Worker {Config.Name}] Task Complete. Reporting back to {message.SenderId}.");
                Console.ResetColor();
            }
        }
    }
}