namespace OzzieAI.Agentica.Providers
{
    using System.Collections.Generic;

    /// <summary>
    /// Defines the universal output contract for all LLM Providers (Grok, Gemini, Ollama).
    /// This interface captures the 'Reasoning' (Content) and the 'Intent' (ToolCalls) 
    /// returned by the model after processing a conversation history.
    /// </summary>
    public interface IChatResponse
    {
        /// <summary>
        /// The natural language text generated by the model. 
        /// This represents the AI's internal thought process, an answer to the user, 
        /// or a rationale for why specific tools are being invoked.
        /// </summary>
        string? Content { get; set; }

        /// <summary>
        /// A collection of formal requests to execute functional capabilities. 
        /// If the model determines that a task requires external action (e.g., File IO, Web Search), 
        /// this list will contain the specific <see cref="ToolCall"/> instructions.
        /// </summary>
        List<ToolCall>? ToolCalls { get; set; }
    }
}