namespace OzzieAI.Agentica.Providers
{
    /// <summary>
    /// Represents a formal request from the Intelligence Engine (LLM) to execute a specific functional capability.
    /// Acts as the bridge between the model's 'Intent' and the system's 'Action'.
    /// </summary>
    public class ToolCall
    {
        /// <summary>
        /// A unique identifier provided by the LLM (e.g., Grok or OpenAI) to track this specific request.
        /// This ID must be returned in the tool result message to maintain the conversation's logical thread.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// The unique registration name of the tool to be invoked (e.g., "file_manager" or "terminal").
        /// This must match the <see cref="IAgentTool.Name"/> property.
        /// </summary>
        public string ToolName { get; set; } = string.Empty;

        /// <summary>
        /// The JSON-formatted string containing the specific parameters generated by the LLM.
        /// This string is passed directly to the <see cref="IAgentTool.ExecuteAsync(string)"/> method for parsing.
        /// </summary>
        public string ArgumentsJson { get; set; } = string.Empty;
    }
}