namespace OzzieAI.Agentica.Agents
{

    using System.Collections.Generic;
    using System.Text.Json.Serialization;


    /// <summary>
    /// Represents the dynamic swarm hierarchy generated by the Boss LLM.
    /// </summary>
    public class SwarmDeploymentPlan
    {
        [JsonPropertyName("manager_name")]
        public string ManagerName { get; set; } = string.Empty;

        [JsonPropertyName("manager_directive")]
        public string ManagerDirective { get; set; } = string.Empty;

        [JsonPropertyName("workers")]
        public List<WorkerDeploymentPlan> Workers { get; set; } = new();
    }

    /// <summary>
    /// Represents a single specialized worker dynamically designed for the mission.
    /// </summary>
    public class WorkerDeploymentPlan
    {
        [JsonPropertyName("worker_name")]
        public string WorkerName { get; set; } = string.Empty;

        [JsonPropertyName("system_prompt")]
        public string SystemPrompt { get; set; } = string.Empty;
    }
}