using System;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace OzzieAI.Agentica.Tools
{
    /// <summary>
    /// A high-integrity safety mechanism that uses the Roslyn compiler engine to 
    /// perform real-time syntax analysis on C# code generated by agents.
    /// </summary>
    public class CodeSafetyGateTool : IAgentTool
    {
        /// <summary>
        /// The unique identifier for this tool within the Agentica ecosystem.
        /// </summary>
        public string Name => "code_validator";

        /// <summary>
        /// Detailed instructions for the LLM regarding mandatory validation protocols.
        /// </summary>
        public string Description => "Mandatory: Use this to validate C# code for syntax errors before saving. Provide the raw code string.";

        /// <summary>
        /// Defines the function signature and parameter requirements for the LLM.
        /// </summary>
        /// <returns>A JSON-schema compliant object for LLM function calling.</returns>
        public object GetToolDefinition() => new
        {
            type = "function",
            function = new
            {
                name = Name,
                description = Description,
                parameters = new
                {
                    type = "object",
                    properties = new
                    {
                        code = new
                        {
                            type = "string",
                            description = "The raw C# source code to validate. Do not wrap in markdown blocks."
                        }
                    },
                    required = new[] { "code" }
                }
            }
        };

        /// <summary>
        /// Parses the provided code using Roslyn and returns a detailed diagnostic report.
        /// </summary>
        /// <param name="jsonArguments">The JSON payload containing the 'code' property.</param>
        /// <returns>A string confirming success or a detailed list of syntax errors and their locations.</returns>
        public async Task<string> ExecuteAsync(string jsonArguments)
        {
            try
            {
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var args = JsonSerializer.Deserialize<CodeArgs>(jsonArguments, options);

                if (args == null || string.IsNullOrWhiteSpace(args.Code))
                {
                    return "Validation Error: No code was provided for analysis.";
                }

                // Initialize the Roslyn Syntax Tree parser
                // LanguageVersion.Latest ensures support for the newest C# features
                var syntaxTree = CSharpSyntaxTree.ParseText(args.Code, new CSharpParseOptions(LanguageVersion.Latest));

                // Retrieve all diagnostics (errors, warnings, etc.) from the parser
                var diagnostics = syntaxTree.GetDiagnostics();

                // Filter specifically for Errors (Severity 3)
                var errors = diagnostics
                    .Where(d => d.Severity == DiagnosticSeverity.Error)
                    .ToList();

                if (!errors.Any())
                {
                    // Visual confirmation in the console:
                    ConsoleLogger.WriteLine("\n[ROSLYN GATE]: Syntax Validation Succeeded.", ConsoleColor.Green);

                    return "Validation Passed: The code is syntactically correct and safe to persist.";
                }

                // Aggregate error details including line numbers and character positions
                var errorReport = string.Join("\n", errors.Select(e =>
                    $"Line {e.Location.GetLineSpan().StartLinePosition.Line + 1}: {e.GetMessage()}"));

                // Visual warning in the console:
                ConsoleLogger.WriteLine($"\n[ROSLYN GATE]: Syntax Validation Failed with {errors.Count} error(s).", ConsoleColor.Red);

                return $"Validation Failed. Please fix the following syntax errors:\n{errorReport}";
            }
            catch (JsonException)
            {
                return "Error: Invalid JSON arguments provided to the code_validator.";
            }
            catch (Exception ex)
            {
                return $"Critical Error during validation: {ex.Message}";
            }
        }

        /// <summary>
        /// Data Transfer Object for deserializing LLM tool arguments.
        /// </summary>
        private class CodeArgs
        {
            /// <summary>
            /// The C# code snippet to be analyzed.
            /// </summary>
            public string Code { get; set; } = string.Empty;
        }
    }
}